package org.systemmanager.model;
// Generated 2013-4-14 3:21:50 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Actionmodule generated by hbm2java
 */
public class Actionmodule  implements java.io.Serializable {


     private Integer idActionModule;
     private Actionmodulegroup actionmodulegroup;
     private String name;
     private String url;
     private Set<Roleactionmodulemap> roleactionmodulemaps = new HashSet<Roleactionmodulemap>(0);

    public Actionmodule() {
    }

	
    public Actionmodule(Actionmodulegroup actionmodulegroup, String name) {
        this.actionmodulegroup = actionmodulegroup;
        this.name = name;
    }
    public Actionmodule(Actionmodulegroup actionmodulegroup, String name, String url, Set<Roleactionmodulemap> roleactionmodulemaps) {
       this.actionmodulegroup = actionmodulegroup;
       this.name = name;
       this.url = url;
       this.roleactionmodulemaps = roleactionmodulemaps;
    }
   
    public Integer getIdActionModule() {
        return this.idActionModule;
    }
    
    public void setIdActionModule(Integer idActionModule) {
        this.idActionModule = idActionModule;
    }
    public Actionmodulegroup getActionmodulegroup() {
        return this.actionmodulegroup;
    }
    
    public void setActionmodulegroup(Actionmodulegroup actionmodulegroup) {
        this.actionmodulegroup = actionmodulegroup;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set<Roleactionmodulemap> getRoleactionmodulemaps() {
        return this.roleactionmodulemaps;
    }
    
    public void setRoleactionmodulemaps(Set<Roleactionmodulemap> roleactionmodulemaps) {
        this.roleactionmodulemaps = roleactionmodulemaps;
    }




}


