package org.systemmanager.model;
// Generated 2013-4-14 3:21:50 by Hibernate Tools 3.2.1.GA



/**
 * Departmentmap generated by hbm2java
 */
public class Departmentmap  implements java.io.Serializable {


     private int idDepartment;
     private Department departmentByIdPreDepartment;
     private Department departmentByIdDepartment;
     private String date;

    public Departmentmap() {
    }

	
    public Departmentmap(int idDepartment, Department departmentByIdDepartment, String date) {
        this.idDepartment = idDepartment;
        this.departmentByIdDepartment = departmentByIdDepartment;
        this.date = date;
    }
    public Departmentmap(int idDepartment, Department departmentByIdPreDepartment, Department departmentByIdDepartment, String date) {
       this.idDepartment = idDepartment;
       this.departmentByIdPreDepartment = departmentByIdPreDepartment;
       this.departmentByIdDepartment = departmentByIdDepartment;
       this.date = date;
    }
   
    public int getIdDepartment() {
        return this.idDepartment;
    }
    
    public void setIdDepartment(int idDepartment) {
        this.idDepartment = idDepartment;
    }
    public Department getDepartmentByIdPreDepartment() {
        return this.departmentByIdPreDepartment;
    }
    
    public void setDepartmentByIdPreDepartment(Department departmentByIdPreDepartment) {
        this.departmentByIdPreDepartment = departmentByIdPreDepartment;
    }
    public Department getDepartmentByIdDepartment() {
        return this.departmentByIdDepartment;
    }
    
    public void setDepartmentByIdDepartment(Department departmentByIdDepartment) {
        this.departmentByIdDepartment = departmentByIdDepartment;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


