package org.systemmanager.model;
// Generated 2013-4-14 3:21:50 by Hibernate Tools 3.2.1.GA



/**
 * Roleactionmodulemap generated by hbm2java
 */
public class Roleactionmodulemap  implements java.io.Serializable {


     private Integer idRoleActionModuleMap;
     private Actionmodule actionmodule;
     private Role role;
     private String date;

    public Roleactionmodulemap() {
    }

    public Roleactionmodulemap(Actionmodule actionmodule, Role role, String date) {
       this.actionmodule = actionmodule;
       this.role = role;
       this.date = date;
    }
   
    public Integer getIdRoleActionModuleMap() {
        return this.idRoleActionModuleMap;
    }
    
    public void setIdRoleActionModuleMap(Integer idRoleActionModuleMap) {
        this.idRoleActionModuleMap = idRoleActionModuleMap;
    }
    public Actionmodule getActionmodule() {
        return this.actionmodule;
    }
    
    public void setActionmodule(Actionmodule actionmodule) {
        this.actionmodule = actionmodule;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


