package org.systemmanager.model;
// Generated 2013-4-14 3:21:50 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Integer idRole;
     private String name;
     private String comment;
     private Set<Userrolemap> userrolemaps = new HashSet<Userrolemap>(0);
     private Set<Roleactionmodulemap> roleactionmodulemaps = new HashSet<Roleactionmodulemap>(0);

    public Role() {
    }

	
    public Role(String name) {
        this.name = name;
    }
    public Role(String name, String comment, Set<Userrolemap> userrolemaps, Set<Roleactionmodulemap> roleactionmodulemaps) {
       this.name = name;
       this.comment = comment;
       this.userrolemaps = userrolemaps;
       this.roleactionmodulemaps = roleactionmodulemaps;
    }
   
    public Integer getIdRole() {
        return this.idRole;
    }
    
    public void setIdRole(Integer idRole) {
        this.idRole = idRole;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Set<Userrolemap> getUserrolemaps() {
        return this.userrolemaps;
    }
    
    public void setUserrolemaps(Set<Userrolemap> userrolemaps) {
        this.userrolemaps = userrolemaps;
    }
    public Set<Roleactionmodulemap> getRoleactionmodulemaps() {
        return this.roleactionmodulemaps;
    }
    
    public void setRoleactionmodulemaps(Set<Roleactionmodulemap> roleactionmodulemaps) {
        this.roleactionmodulemaps = roleactionmodulemaps;
    }




}


