package org.systemmanager.model;
// Generated 2013-4-14 3:21:50 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private Department department;
     private String username;
     private String password;
     private String name;
     private String telephone;
     private String job;
     private Set<Userrolemap> userrolemaps = new HashSet<Userrolemap>(0);

    public User() {
    }

	
    public User(Department department, String username, String password, String name) {
        this.department = department;
        this.username = username;
        this.password = password;
        this.name = name;
    }
    public User(Department department, String username, String password, String name, String telephone, String job, Set<Userrolemap> userrolemaps) {
       this.department = department;
       this.username = username;
       this.password = password;
       this.name = name;
       this.telephone = telephone;
       this.job = job;
       this.userrolemaps = userrolemaps;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }
    public Set<Userrolemap> getUserrolemaps() {
        return this.userrolemaps;
    }
    
    public void setUserrolemaps(Set<Userrolemap> userrolemaps) {
        this.userrolemaps = userrolemaps;
    }




}


