package org.dbmanager.model;
// Generated 2013-4-23 23:15:29 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Customaction generated by hbm2java
 */
public class Customaction  implements java.io.Serializable {

     private Integer idCustomAction;
     private String name;
     private String comment;
     private Set<Customsubaction> customsubactions = new HashSet<Customsubaction>(0);

    public Customaction() {
    }

	
    public Customaction(String name) {
        this.name = name;
    }
    public Customaction(String name, String comment, Set<Customsubaction> customsubactions) {
       this.name = name;
       this.comment = comment;
       this.customsubactions = customsubactions;
    }
   
    public Integer getIdCustomAction() {
        return this.idCustomAction;
    }
    
    public void setIdCustomAction(Integer idCustomAction) {
        this.idCustomAction = idCustomAction;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Set<Customsubaction> getCustomsubactions() {
        return this.customsubactions;
    }
    
    public void setCustomsubactions(Set<Customsubaction> customsubactions) {
        this.customsubactions = customsubactions;
    }




}


