package org.dbmanager.model;
// Generated 2013-4-23 23:15:29 by Hibernate Tools 3.2.1.GA



/**
 * Customtablecustomactionmap generated by hbm2java
 */
public class Customtablecustomactionmap  implements java.io.Serializable {


     private Integer idCustomTableCustomActionMap;
     private int idCustomTable;
     private int idCustomAction;

    public Customtablecustomactionmap() {
    }

    public Customtablecustomactionmap(int idCustomTable, int idCustomAction) {
       this.idCustomTable = idCustomTable;
       this.idCustomAction = idCustomAction;
    }
   
    public Integer getIdCustomTableCustomActionMap() {
        return this.idCustomTableCustomActionMap;
    }
    
    public void setIdCustomTableCustomActionMap(Integer idCustomTableCustomActionMap) {
        this.idCustomTableCustomActionMap = idCustomTableCustomActionMap;
    }
    public int getIdCustomTable() {
        return this.idCustomTable;
    }
    
    public void setIdCustomTable(int idCustomTable) {
        this.idCustomTable = idCustomTable;
    }
    public int getIdCustomAction() {
        return this.idCustomAction;
    }
    
    public void setIdCustomAction(int idCustomAction) {
        this.idCustomAction = idCustomAction;
    }




}


