package org.dbmanager.model;
// Generated 2013-4-23 23:15:29 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Customtable generated by hbm2java
 */
public class Customtable  implements java.io.Serializable {


     private Integer idCustomTable;
     private String name;
     private String showName;
     private int type;
     private String comment;
     private Set<Customtablecolumn> customtablecolumns = new HashSet<Customtablecolumn>(0);

    public Customtable() {
    }

	
    public Customtable(String name, String showName, int type) {
        this.name = name;
        this.showName = showName;
        this.type = type;
    }
    public Customtable(String name, String showName, int type, String comment, Set<Customtablecolumn> customtablecolumns) {
       this.name = name;
       this.showName = showName;
       this.type = type;
       this.comment = comment;
       this.customtablecolumns = customtablecolumns;
    }
   
    public Integer getIdCustomTable() {
        return this.idCustomTable;
    }
    
    public void setIdCustomTable(Integer idCustomTable) {
        this.idCustomTable = idCustomTable;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getShowName() {
        return this.showName;
    }
    
    public void setShowName(String showName) {
        this.showName = showName;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Set<Customtablecolumn> getCustomtablecolumns() {
        return this.customtablecolumns;
    }
    
    public void setCustomtablecolumns(Set<Customtablecolumn> customtablecolumns) {
        this.customtablecolumns = customtablecolumns;
    }




}


