package org.dbmanager.model;
// Generated 2013-4-23 23:15:29 by Hibernate Tools 3.2.1.GA



/**
 * Customtablequeryactionmap generated by hbm2java
 */
public class Customtablequeryactionmap  implements java.io.Serializable {


     private Integer idCustomTableQueryActionMap;
     private int idCustomTable;
     private int idCustomQueryAction;

    public Customtablequeryactionmap() {
    }

    public Customtablequeryactionmap(int idCustomTable, int idCustomQueryAction) {
       this.idCustomTable = idCustomTable;
       this.idCustomQueryAction = idCustomQueryAction;
    }
   
    public Integer getIdCustomTableQueryActionMap() {
        return this.idCustomTableQueryActionMap;
    }
    
    public void setIdCustomTableQueryActionMap(Integer idCustomTableQueryActionMap) {
        this.idCustomTableQueryActionMap = idCustomTableQueryActionMap;
    }
    public int getIdCustomTable() {
        return this.idCustomTable;
    }
    
    public void setIdCustomTable(int idCustomTable) {
        this.idCustomTable = idCustomTable;
    }
    public int getIdCustomQueryAction() {
        return this.idCustomQueryAction;
    }
    
    public void setIdCustomQueryAction(int idCustomQueryAction) {
        this.idCustomQueryAction = idCustomQueryAction;
    }




}


