package org.dbmanager.model;
// Generated 2013-4-23 23:15:29 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Customqueryaction generated by hbm2java
 */
public class Customqueryaction  implements java.io.Serializable {


     private Integer idCustomQueryAction;
     private String name;
     private String comment;
     private Set<Customquerysubaction> customquerysubactions = new HashSet<Customquerysubaction>(0);

    public Customqueryaction() {
    }

	
    public Customqueryaction(String name) {
        this.name = name;
    }
    public Customqueryaction(String name, String comment, Set<Customquerysubaction> customquerysubactions) {
       this.name = name;
       this.comment = comment;
       this.customquerysubactions = customquerysubactions;
    }
   
    public Integer getIdCustomQueryAction() {
        return this.idCustomQueryAction;
    }
    
    public void setIdCustomQueryAction(Integer idCustomQueryAction) {
        this.idCustomQueryAction = idCustomQueryAction;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Set<Customquerysubaction> getCustomquerysubactions() {
        return this.customquerysubactions;
    }
    
    public void setCustomquerysubactions(Set<Customquerysubaction> customquerysubactions) {
        this.customquerysubactions = customquerysubactions;
    }




}


