package org.dbmanager.model;
// Generated 2013-4-23 23:15:29 by Hibernate Tools 3.2.1.GA



/**
 * Customtablecolumn generated by hbm2java
 */
public class Customtablecolumn  implements java.io.Serializable {


     private Integer idCustomTableColumn;
     private Customtable customtable;
     private String columnName;
     private String columnShowName;
     private boolean columnIsHide;
     private boolean columnIsPrimaryKey;
     private String columnType;
     private String columnRestrict;
     private String columnDefualtValue;
     private String columnControlType;
     private String columnControlDefine;
     private String columnControlValueType;
     private String comment;

    public Customtablecolumn() {
    }

	
    public Customtablecolumn(Customtable customtable, String columnName, String columnShowName, boolean columnIsHide, boolean columnIsPrimaryKey, String columnType) {
        this.customtable = customtable;
        this.columnName = columnName;
        this.columnShowName = columnShowName;
        this.columnIsHide = columnIsHide;
        this.columnIsPrimaryKey = columnIsPrimaryKey;
        this.columnType = columnType;
    }
    public Customtablecolumn(Customtable customtable, String columnName, String columnShowName, boolean columnIsHide, boolean columnIsPrimaryKey, String columnType, String columnRestrict, String columnDefualtValue, String columnControlType, String columnControlDefine, String columnControlValueType, String comment) {
       this.customtable = customtable;
       this.columnName = columnName;
       this.columnShowName = columnShowName;
       this.columnIsHide = columnIsHide;
       this.columnIsPrimaryKey = columnIsPrimaryKey;
       this.columnType = columnType;
       this.columnRestrict = columnRestrict;
       this.columnDefualtValue = columnDefualtValue;
       this.columnControlType = columnControlType;
       this.columnControlDefine = columnControlDefine;
       this.columnControlValueType = columnControlValueType;
       this.comment = comment;
    }
   
    public Integer getIdCustomTableColumn() {
        return this.idCustomTableColumn;
    }
    
    public void setIdCustomTableColumn(Integer idCustomTableColumn) {
        this.idCustomTableColumn = idCustomTableColumn;
    }
    public Customtable getCustomtable() {
        return this.customtable;
    }
    
    public void setCustomtable(Customtable customtable) {
        this.customtable = customtable;
    }
    public String getColumnName() {
        return this.columnName;
    }
    
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }
    public String getColumnShowName() {
        return this.columnShowName;
    }
    
    public void setColumnShowName(String columnShowName) {
        this.columnShowName = columnShowName;
    }
    public boolean isColumnIsHide() {
        return this.columnIsHide;
    }
    
    public void setColumnIsHide(boolean columnIsHide) {
        this.columnIsHide = columnIsHide;
    }
    public boolean isColumnIsPrimaryKey() {
        return this.columnIsPrimaryKey;
    }
    
    public void setColumnIsPrimaryKey(boolean columnIsPrimaryKey) {
        this.columnIsPrimaryKey = columnIsPrimaryKey;
    }
    public String getColumnType() {
        return this.columnType;
    }
    
    public void setColumnType(String columnType) {
        this.columnType = columnType;
    }
    public String getColumnRestrict() {
        return this.columnRestrict;
    }
    
    public void setColumnRestrict(String columnRestrict) {
        this.columnRestrict = columnRestrict;
    }
    public String getColumnDefualtValue() {
        return this.columnDefualtValue;
    }
    
    public void setColumnDefualtValue(String columnDefualtValue) {
        this.columnDefualtValue = columnDefualtValue;
    }
    public String getColumnControlType() {
        return this.columnControlType;
    }
    
    public void setColumnControlType(String columnControlType) {
        this.columnControlType = columnControlType;
    }
    public String getColumnControlDefine() {
        return this.columnControlDefine;
    }
    
    public void setColumnControlDefine(String columnControlDefine) {
        this.columnControlDefine = columnControlDefine;
    }
    public String getColumnControlValueType() {
        return this.columnControlValueType;
    }
    
    public void setColumnControlValueType(String columnControlValueType) {
        this.columnControlValueType = columnControlValueType;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


